version: 1.0.0.{build}
os: Visual Studio 2015
install:
- ps: dnvm install 1.0.0-rc1-update1
before_build:
- ps: >-
    dnu restore

    nuget restore
build:
  verbosity: minimal
test_script:
- ps: >-
    cd .\src\Polyglot.Tests.Dnx

    dnx test


    cd ..\

    %xunit20%\xunit.console.x86 .\Polyglot.Tests.Net451\bin\Debug\Polyglot.Tests.Net451.dll" -appveyor
